import './globals.css';
import type { Metadata } from 'next';
import { HabitFont } from '@/app/fonts';
import { QueryClientProvider } from '@/commons/apis/queryClientProvider';
import MobileViewLayout from '@/commons/layouts/MobileViewLayout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={HabitFont.className}>
        <QueryClientProvider>{children}</QueryClientProvider>
      </body>
    </html>
  );
}
