import type { Metadata } from 'next';
import './globals.css';
import { HabitFont } from '@/app/fonts';
import { QueryClientProvider } from '@/commons/apis/queryClientProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider>
      <html lang="en">
        <body className={HabitFont.className}>{children}</body>
      </html>
    </QueryClientProvider>
  );
}
